"""nora citation — deterministic citation-hygiene backend (Stages 6+7).

Migrates the mechanical checks that the nora-citation-auditor skill used to
perform by prompt (undefined keys, unused entries, malformed cite commands,
oversized cite clusters, duplicate keys/DOIs, missing fields) into scripted
checks, and adds hygiene normalization (proxy DOIs, page-range dashes,
author name format) with a conservative apply model:

- 'lint' and 'normalize' are read-only
- 'fix' prints a diff by default and only writes with --apply, after
  backing the file up to .nora/citation/backups/
- 'keygen' only proposes keys: renaming a key touches .tex, which this
  CLI never edits
- fixes are targeted string substitutions — entries are never reordered
  or reformatted wholesale

The claim-without-citation check is explicitly a heuristic (a fixed verb
list); its findings are leads for review, not verdicts.
"""

from __future__ import annotations

import argparse
import difflib
import re
import shutil
from datetime import datetime
from pathlib import Path

from . import papers as ps

HELP_TEXT = """\
Nora citation auditor

Commands:
  nora citation init       Create .nora/citation/ skeleton in the current project
  nora citation lint       Run all mechanical checks over .bib/.tex (alias: check);
                           --write saves LINT_REPORT.md
  nora citation normalize  Show the hygiene-normalization diff for .bib files (read-only)
  nora citation fix        Apply SAFE_FIX normalizations (--apply to write; the original
                           is backed up to .nora/citation/backups/ first)
  nora citation keygen     Propose convention-conforming BibTeX keys (report-only:
                           renaming keys touches .tex, which this CLI never edits)
  nora citation doctor     Check whether citation module files exist

Checks: undefined/unused citation keys, malformed cite commands, oversized cite
clusters, duplicate keys/DOIs, missing fields, proxy DOIs, page-range dashes,
author name format, and a clearly-labeled heuristic for uncited technical claims.

Judgment work (claim-support review, fuzzy-duplicate adjudication, review-queue
curation) stays in the skill:
  /nora-citation-auditor check-bibtex | check-latex-citations | report | audit-claim-support"""

GENERATED_HEADER = "<!-- Generated by 'nora citation lint --write'. Do not edit by hand. -->"

SKIP_DIRS = {".git", ".nora", "node_modules", "__pycache__", ".venv", "venv",
             "build", "_build", "out"}

CITE_CLUSTER_MAX = 5

# Heuristic only: sentences containing these and no \cite are *leads*, not verdicts.
CLAIM_VERBS = ["proves", "proven", "demonstrates", "demonstrated", "outperforms",
               "guarantees", "state-of-the-art", "sota"]

REQUIRED_FIELDS = {
    "article": ["journal"],
    "inproceedings": ["booktitle"],
    "conference": ["booktitle"],
    "book": ["publisher"],
}

# Entry types where a stable product/spec key is acceptable, so keygen skips them.
KEYGEN_SKIP_TYPES = {"misc", "manual", "online", "standard", "techreport"}

PROXY_DOI_RE = re.compile(r"https?://doi[.-]org[.-][A-Za-z0-9.-]+/")
CITE_RE = re.compile(r"\\(?:[a-zA-Z]*cite[a-zA-Z]*)\s*(?:\[[^\]]*\])?\s*\{([^}]*)\}")
NOCITE_RE = re.compile(r"\\nocite\s*\{([^}]*)\}")
KEY_OK_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.:+/-]*$")


def _base() -> Path:
    from .cli import find_workspace_root
    return find_workspace_root() or Path.cwd()


def _discover(base: Path, suffix: str) -> list[Path]:
    found = []
    for path in sorted(base.rglob(f"*{suffix}")):
        if not any(part in SKIP_DIRS or part.startswith("_minted")
                   for part in path.relative_to(base).parts):
            found.append(path)
    return found


def _resolve_files(base: Path, args) -> tuple[list[Path], list[Path]]:
    bibs = [Path(b) for b in args.bib] if getattr(args, "bib", None) else _discover(base, ".bib")
    texs = [Path(t) for t in getattr(args, "tex", None) or []] or _discover(base, ".tex")
    return bibs, texs


# --- findings ----------------------------------------------------------------

def _finding(label: str, check: str, message: str) -> dict:
    return {"label": label, "check": check, "message": message}


def lint_bib(bibs: list[Path]) -> list[dict]:
    findings = []
    entries = []
    for bib in bibs:
        text = bib.read_text()
        for e in ps.parse_bibtex(text):
            e["file"] = str(bib)
            entries.append(e)

    seen_keys: dict = {}
    for e in entries:
        seen_keys.setdefault(e["key"], []).append(e)
    for key, group in sorted(seen_keys.items()):
        if len(group) > 1:
            files = ", ".join(x["file"] for x in group)
            findings.append(_finding(
                "AUTO_SAFE", "duplicate_key",
                f"key '{key}' defined {len(group)} times ({files}) — which entry to keep is a human decision"))

    by_doi: dict = {}
    for e in entries:
        doi = e["fields"].get("doi")
        if doi:
            by_doi.setdefault(ps.normalize_doi(doi), []).append(e["key"])
    for doi, keys in sorted(by_doi.items()):
        if len(keys) > 1:
            findings.append(_finding(
                "REVIEW_REQUIRED", "duplicate_doi",
                f"DOI {doi} appears on: {', '.join(keys)}"))

    for e in entries:
        missing = [f for f in ["title", "author", "year"] if f not in e["fields"]]
        missing += [f for f in REQUIRED_FIELDS.get(e["type"], []) if f not in e["fields"]]
        if missing:
            findings.append(_finding(
                "DO_NOT_APPLY", "missing_fields",
                f"{e['key']} (@{e['type']}): missing {', '.join(missing)} — flag only, never guessed"))
    return findings


def lint_tex(texs: list[Path], bibs: list[Path]) -> list[dict]:
    findings = []
    defined = set()
    for bib in bibs:
        for e in ps.parse_bibtex(bib.read_text()):
            defined.add(e["key"])

    cited: dict = {}
    nocite_all = False
    for tex in texs:
        for lineno, line in enumerate(tex.read_text().splitlines(), 1):
            code = line.split("%", 1)[0]
            for m in NOCITE_RE.finditer(code):
                if m.group(1).strip() == "*":
                    nocite_all = True
            for m in CITE_RE.finditer(code):
                keys = [k.strip() for k in m.group(1).split(",")]
                loc = f"{tex}:{lineno}"
                if not any(keys) or m.group(1).strip() == "":
                    findings.append(_finding(
                        "AUTO_SAFE", "malformed_cite", f"empty citation command at {loc}"))
                    continue
                for k in keys:
                    if not k:
                        findings.append(_finding(
                            "AUTO_SAFE", "malformed_cite",
                            f"empty key in citation list at {loc}"))
                    elif not KEY_OK_RE.match(k):
                        findings.append(_finding(
                            "AUTO_SAFE", "malformed_cite",
                            f"suspicious key '{k}' at {loc} (whitespace or illegal characters)"))
                    else:
                        cited.setdefault(k, loc)
                if len(keys) > CITE_CLUSTER_MAX:
                    findings.append(_finding(
                        "REVIEW_REQUIRED", "cite_cluster",
                        f"{len(keys)} keys in one citation at {loc} (max {CITE_CLUSTER_MAX}) — consider splitting or pruning"))

    for k, loc in sorted(cited.items()):
        if defined and k not in defined:
            findings.append(_finding(
                "BLOCKED", "undefined_key", f"'{k}' cited at {loc} but not defined in any .bib"))
    if nocite_all:
        findings.append(_finding(
            "REVIEW_REQUIRED", "unused_entry",
            r"\nocite{*} present — unused-entry check skipped"))
    else:
        for k in sorted(defined - set(cited)):
            findings.append(_finding(
                "REVIEW_REQUIRED", "unused_entry",
                f"'{k}' defined but never cited (may be intentional)"))
    return findings


def lint_claims(texs: list[Path]) -> list[dict]:
    """HEURISTIC: technical-claim verbs with no citation in the same sentence.

    Findings are leads for a human (or audit-claim-support), not verdicts.
    """
    findings = []
    for tex in texs:
        text = "\n".join(l.split("%", 1)[0] for l in tex.read_text().splitlines())
        for m in re.finditer(r"[^.!?]*[.!?]", text):
            sentence = m.group(0)
            lowered = sentence.lower()
            if any(v in lowered for v in CLAIM_VERBS) and "cite" not in lowered:
                lineno = text[:m.start()].count("\n") + 1
                snippet = " ".join(sentence.split())[:90]
                findings.append(_finding(
                    "REVIEW_REQUIRED", "uncited_claim",
                    f'heuristic: possible uncited claim at {tex}:~{lineno}: "{snippet}..."'))
    return findings


# --- SAFE_FIX normalizations ---------------------------------------------------

def _fix_pages(match: re.Match) -> str:
    inner = re.sub(r"(?<=\d)\s*-\s*(?=\d)", "--", match.group(2))
    return match.group(1) + inner + match.group(3)


def _fix_authors_value(value: str):
    """'First Last and A B' -> 'Last, First and B, A' — only unambiguous
    two-token names; anything else is left alone."""
    changed = False
    out = []
    for author in value.split(" and "):
        tokens = author.strip().split()
        if "," not in author and len(tokens) == 2:
            out.append(f"{tokens[1]}, {tokens[0]}")
            changed = True
        else:
            out.append(author.strip())
    return " and ".join(out), changed


def normalized_bib_text(text: str) -> tuple[str, list[str]]:
    """Return (new_text, change descriptions). Targeted substitutions only."""
    changes = []
    new = PROXY_DOI_RE.sub("https://doi.org/", text)
    if new != text:
        changes.append("proxy DOI hosts rewritten to https://doi.org/")
    text = new

    def pages_repl(m):
        return _fix_pages(m)

    new = re.sub(r"(pages\s*=\s*[{\"])([^}\"]*)([}\"])", pages_repl, text)
    if new != text:
        changes.append("page ranges use -- instead of -")
    text = new

    def author_repl(m):
        fixed, changed = _fix_authors_value(m.group(2))
        author_repl.changed |= changed
        return m.group(1) + fixed + m.group(3)

    author_repl.changed = False
    new = re.sub(r"(author\s*=\s*[{\"])([^}\"]*)([}\"])", author_repl, text)
    if author_repl.changed:
        changes.append("unambiguous author names reformatted as 'Lastname, Firstname'")
    text = new
    return text, changes


# --- subcommands ----------------------------------------------------------------

def cmd_lint(base: Path, args) -> int:
    bibs, texs = _resolve_files(base, args)
    if not bibs and not texs:
        print("No .bib or .tex files found in the workspace.")
        return 1
    print(f"Scanning {len(bibs)} .bib and {len(texs)} .tex file(s)...")
    if len(bibs) > 1 and not args.bib:
        print(f"NOTE: {len(bibs)} .bib files treated as one merged bibliography"
              " (pass --bib to scope).")

    findings = lint_bib(bibs) + lint_tex(texs, bibs) + lint_claims(texs)
    _, safe_changes = normalized_bib_text("\n".join(b.read_text() for b in bibs))
    lines = []
    if not findings and not safe_changes:
        lines.append("No findings. Bibliography and citations look clean.")
    for f in findings:
        lines.append(f"{f['label']} [{f['check']}] {f['message']}")
    for c in safe_changes:
        lines.append(f"SAFE_FIX [normalize] {c} (run 'nora citation fix --apply')")
    print("\n".join(lines))
    print()
    print(f"{len(findings)} finding(s), {len(safe_changes)} normalization group(s).")
    print("Nothing was modified; no finding is ever auto-applied by lint.")

    if args.write:
        report = _base_citation_dir(base) / "LINT_REPORT.md"
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text("\n".join(
            [GENERATED_HEADER, "", "# Citation Lint Report", "",
             f"- Files: {len(bibs)} .bib, {len(texs)} .tex", "", "```text"]
            + lines + ["```", ""]))
        print(f"Written: {report}")
    return 0


def _base_citation_dir(base: Path) -> Path:
    return base / ".nora" / "citation"


def cmd_normalize(base: Path, args) -> int:
    bibs, _ = _resolve_files(base, args)
    if not bibs:
        print("No .bib files found.")
        return 1
    any_changes = False
    for bib in bibs:
        old = bib.read_text()
        new, changes = normalized_bib_text(old)
        if not changes:
            continue
        any_changes = True
        print(f"--- {bib} (read-only preview; apply with 'nora citation fix --apply')")
        for c in changes:
            print(f"  {c}")
        for line in difflib.unified_diff(old.splitlines(), new.splitlines(),
                                         lineterm="", n=1):
            print(line)
    if not any_changes:
        print("Nothing to normalize; .bib files already conform.")
    return 0


def cmd_fix(base: Path, args) -> int:
    bibs, _ = _resolve_files(base, args)
    if not bibs:
        print("No .bib files found.")
        return 1
    to_fix = []
    for bib in bibs:
        old = bib.read_text()
        new, changes = normalized_bib_text(old)
        if changes:
            to_fix.append((bib, old, new, changes))
    if not to_fix:
        print("Nothing to fix; .bib files already conform.")
        return 0

    if not args.apply:
        for bib, old, new, changes in to_fix:
            print(f"{bib}: {'; '.join(changes)}")
        print()
        print(f"Dry run: {len(to_fix)} file(s) would change. Re-run with --apply to write")
        print("(originals are backed up to .nora/citation/backups/ first).")
        return 0

    backups = _base_citation_dir(base) / "backups"
    backups.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    for bib, old, new, changes in to_fix:
        backup = backups / f"{stamp}-{bib.name}"
        shutil.copy(bib, backup)
        bib.write_text(new)
        print(f"fixed {bib}: {'; '.join(changes)}")
        print(f"  backup: {backup}")
    return 0


def cmd_keygen(base: Path, args) -> int:
    bibs, _ = _resolve_files(base, args)
    if not bibs:
        print("No .bib files found.")
        return 1
    proposals = []
    taken = []
    entries = []
    for bib in bibs:
        entries += ps.parse_bibtex(bib.read_text())
    existing = [{"id": e["key"]} for e in entries]
    for e in entries:
        if e["type"] in KEYGEN_SKIP_TYPES or "author" not in e["fields"]:
            continue  # product/spec-style entries may keep stable product keys
        fields = ps.bibtex_to_paper_fields(e)
        expected = ps.make_id([p for p in existing if p["id"] != e["key"]],
                              fields["authors"], fields["year"], fields["title"])
        if e["key"] != expected:
            proposals.append((e["key"], expected))
    if not proposals:
        print("All keys already follow the convention (surname+year+first substantive word).")
        return 0
    print("Proposed key renames (NEVER applied automatically — renaming touches .tex,")
    print("which this CLI does not edit; apply by hand or ask the skill to draft a patch):")
    for old, new in proposals:
        print(f"  {old} -> {new}")
    return 0


def cmd_module_init(base: Path) -> int:
    from .cli import nora_home, MODULES
    mod_dir = _base_citation_dir(base)
    if mod_dir.is_dir():
        print("Citation audit state already exists: .nora/citation/")
        return 0
    mod_dir.mkdir(parents=True)
    src = nora_home() / "skills" / "nora-citation-auditor" / "templates" / "citation"
    for item in src.iterdir():
        shutil.copy(item, mod_dir / item.name)
    if not (base / ".nora" / "PROJECT_STATE.yaml").is_file():
        print("Note: no full Nora project state found (.nora/PROJECT_STATE.yaml missing).")
        print("Initialized citation-audit-only (standalone) state in:")
    else:
        print("Initialized citation audit state in:")
    print(f"  {mod_dir}")
    return 0


def cmd_module_doctor(base: Path) -> int:
    from .cli import MODULES
    mod = MODULES["citation"]
    mod_dir = _base_citation_dir(base)
    if not mod_dir.is_dir():
        print("ERROR: .nora/citation/ not found.")
        print("Run 'nora citation init' first.")
        return 1
    print(mod["doctor_intro"])
    missing = False
    for f in mod["files"]:
        if (base / f).is_file():
            print(f"OK: {f}")
        else:
            print(f"MISSING: {f}")
            missing = True
    if not missing:
        print(mod["doctor_ok"])
        return 0
    print(mod["doctor_incomplete"])
    return 1


# --- dispatch --------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="nora citation", add_help=True)
    sub = parser.add_subparsers(dest="subcmd")

    for name in ("lint", "check"):
        p = sub.add_parser(name, help="run all mechanical checks (check = alias of lint)")
        p.add_argument("--bib", action="append", metavar="FILE")
        p.add_argument("--tex", action="append", metavar="FILE")
        p.add_argument("--write", action="store_true", help="save LINT_REPORT.md")

    normalize = sub.add_parser("normalize", help="show the hygiene diff (read-only)")
    normalize.add_argument("--bib", action="append", metavar="FILE")

    fix = sub.add_parser("fix", help="apply SAFE_FIX normalizations")
    fix.add_argument("--bib", action="append", metavar="FILE")
    fix.add_argument("--apply", action="store_true",
                     help="write changes (originals backed up first); default is a dry run")

    keygen = sub.add_parser("keygen", help="propose convention-conforming keys (report-only)")
    keygen.add_argument("--bib", action="append", metavar="FILE")

    sub.add_parser("init", help="create .nora/citation/")
    sub.add_parser("doctor", help="check citation module state")
    return parser


def cmd_citation(argv: list[str]) -> int:
    if not argv or argv[0] == "help":
        print(HELP_TEXT)
        return 0
    try:
        args = build_parser().parse_args(argv)
    except SystemExit as e:
        return int(e.code or 0)

    base = _base()
    if args.subcmd in ("lint", "check"):
        return cmd_lint(base, args)
    if args.subcmd == "normalize":
        return cmd_normalize(base, args)
    if args.subcmd == "fix":
        return cmd_fix(base, args)
    if args.subcmd == "keygen":
        return cmd_keygen(base, args)
    if args.subcmd == "init":
        return cmd_module_init(base)
    if args.subcmd == "doctor":
        return cmd_module_doctor(base)
    print(HELP_TEXT)
    return 0
