"""nora literature — structured literature backend (Stage 3).

papers.yaml is the single source of truth (see papers.py). Markdown files
under .nora/literature/ are generated views. State transitions go through
'mark', which enforces the decision gate mechanically: promoting a paper to
a gated status requires an approved entry in .nora/decisions/decisions.yaml.

This is the first argparse subtree in the CLI; the legacy hand-written
dispatch for other commands is intentionally untouched.
"""

from __future__ import annotations

import argparse
import difflib
import re
from datetime import date
from pathlib import Path

from . import papers as ps
from . import sources as src

HELP_TEXT = """\
Nora literature manager

Commands:
  nora literature init      Create .nora/literature/ with an empty papers.yaml
  nora literature search    Query external sources (--query "..."; arXiv/OpenAlex/S2/Crossref/DBLP,
                            keyless, cached permanently, --refresh to re-fetch); hits enter candidate state
  nora literature ingest    Add candidate papers (--bibtex FILE | --titles FILE | --title ... manual entry)
  nora literature dedup     Report likely duplicates in papers.yaml (never merges automatically)
  nora literature queue     List papers in the reading queue (status queued/reading)
  nora literature mark      Change a paper's status, roles (--role), or note (--note);
                            gated statuses need --decision <approved id>
  nora literature coverage  Compact role x status coverage report
  nora literature render    Regenerate READING_QUEUE.md and RELATED_WORK_MAP.md from papers.yaml
  nora literature doctor    Check literature state (papers.yaml parses, decision gate consistent)

Statuses: candidate -> queued -> reading -> read -> proposed_cite -> cited / rejected
Promotions to read/proposed_cite/cited/rejected require an approved decision
(.nora/decisions/decisions.yaml) passed via 'mark --decision'.

Judgment work (what to read, why it matters) lives in the skill:
  /nora-literature-manager triage | reading-queue | paper-note | related-work-map | search"""

LEGACY_FILES = ["LITERATURE_LOG.md", "READING_QUEUE.md", "RELATED_WORK_MAP.md"]

GENERATED_HEADER = "<!-- Generated by 'nora literature render' from papers.yaml. Do not edit by hand. -->"

# Conservative fuzzy-title threshold: only near-identical titles qualify,
# and they are reported as review candidates, never merged.
FUZZY_THRESHOLD = 0.93


def _today() -> str:
    return date.today().isoformat()


def _base(explicit: Path | None = None) -> Path:
    from .cli import find_workspace_root
    return explicit or find_workspace_root() or Path.cwd()


def _lit_dir(base: Path) -> Path:
    return base / ".nora" / "literature"


def read_decisions(base: Path) -> dict:
    """Loose scan of decisions.yaml: id -> status. Comment lines ignored."""
    path = base / ".nora" / "decisions" / "decisions.yaml"
    decisions: dict = {}
    if not path.is_file():
        return decisions
    current = None
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            continue
        m = re.match(r"-\s+id:\s*(\S+)", stripped)
        if m:
            current = m.group(1)
            continue
        m = re.match(r"status:\s*(\S+)", stripped)
        if m and current:
            decisions[current] = m.group(1)
    return decisions


# --- subcommands -------------------------------------------------------------


def cmd_init(base: Path) -> int:
    lit = _lit_dir(base)
    if ps.papers_path(base).is_file():
        print("Literature state already exists: .nora/literature/papers.yaml")
        return 0
    if lit.is_dir() and any((lit / f).is_file() for f in LEGACY_FILES):
        print("Found a pre-0.4 literature layout (markdown files, no papers.yaml).")
        print("The literature module was redesigned around papers.yaml; there is no automatic migration.")
        print("Move the old files aside (they are yours to keep), then re-run 'nora literature init'.")
        return 1
    (lit / "PAPER_NOTES").mkdir(parents=True, exist_ok=True)
    ps.save(base, [])
    if not (base / ".nora" / "PROJECT_STATE.yaml").is_file():
        print("Note: no full Nora project state found (.nora/PROJECT_STATE.yaml missing).")
        print("Initialized literature-only (standalone) state in:")
    else:
        print("Initialized literature state in:")
    print(f"  {lit}")
    print("Single source of truth: papers.yaml (use 'nora literature' commands, not hand edits).")
    return 0


def _match_existing(papers: list[dict], fields: dict):
    """Return the existing paper that duplicates `fields`, if any (exact only)."""
    doi = fields.get("doi")
    arxiv = fields.get("arxiv")
    title = ps.normalize_title(fields["title"])
    for p in papers:
        if doi and p["doi"] and ps.normalize_doi(p["doi"]) == ps.normalize_doi(doi):
            return p
        if arxiv and p["arxiv"] and p["arxiv"] == arxiv:
            return p
        if title and ps.normalize_title(p["title"]) == title:
            return p
    return None


def _clean(value):
    """Collapse all whitespace: papers.yaml is line-based, values must be single-line."""
    return " ".join(value.split()) if isinstance(value, str) else value


def _add_paper(papers: list[dict], fields: dict, source: str, note=None) -> dict:
    fields = {k: _clean(v) for k, v in fields.items()}
    paper = {
        "id": ps.make_id(papers, fields.get("authors") or [], fields.get("year"), fields["title"]),
        "title": fields["title"],
        "authors": [_clean(a) for a in fields.get("authors") or []],
        "year": fields.get("year"),
        "venue": fields.get("venue"),
        "doi": fields.get("doi"),
        "arxiv": fields.get("arxiv"),
        "url": fields.get("url"),
        "source": source,
        "status": "candidate",
        "roles": [],
        "decision": None,
        "added": _today(),
        "updated": _today(),
        "note": _clean(note),
    }
    papers.append(paper)
    return paper


def cmd_ingest(base: Path, args) -> int:
    try:
        papers = ps.load(base)
    except ps.PapersError as e:
        print(f"ERROR: {e}")
        return 1

    batches: list[tuple[dict, str]] = []
    if args.bibtex:
        text = Path(args.bibtex).read_text()
        entries = ps.parse_bibtex(text)
        if not entries:
            print(f"No BibTeX entries found in {args.bibtex}.")
            return 1
        batches = [(ps.bibtex_to_paper_fields(e), "bibtex") for e in entries]
    elif args.titles:
        lines = [l.strip() for l in Path(args.titles).read_text().splitlines()]
        titles = [l for l in lines if l and not l.startswith("#")]
        if not titles:
            print(f"No titles found in {args.titles}.")
            return 1
        batches = [({"title": t, "authors": []}, "title_list") for t in titles]
    elif args.title:
        fields = {
            "title": args.title,
            "authors": args.author or [],
            "year": args.year,
            "venue": args.venue,
            "doi": ps.normalize_doi(args.doi) if args.doi else None,
            "arxiv": args.arxiv,
            "url": args.url,
        }
        batches = [(fields, "manual")]
    else:
        print("Nothing to ingest: pass --bibtex FILE, --titles FILE, or --title ... for a manual entry.")
        return 1

    added, skipped = [], []
    for fields, source in batches:
        existing = _match_existing(papers, fields)
        if existing:
            skipped.append((fields["title"], existing["id"]))
        else:
            added.append(_add_paper(papers, fields, source, note=getattr(args, "note", None)))

    if added:
        ps.save(base, papers)
    for paper in added:
        print(f"added: {paper['id']}  {paper['title']} [candidate]")
    for title, dup_id in skipped:
        print(f"skipped (already present as {dup_id}): {title}")
    print(f"{len(added)} added, {len(skipped)} skipped. Total papers: {len(papers)}.")
    return 0


def _cache_dir(base: Path) -> Path:
    return _lit_dir(base) / "cache"


def write_top_candidates(base: Path, papers: list[dict]) -> Path:
    """Generated view: candidate papers ranked by mechanical signals only
    (citations / recency / how many sources agreed — from the search cache).
    Relevance judgment stays with triage; this file just orders the pile."""
    signals = src.cached_signals(_cache_dir(base))

    def paper_signals(p: dict):
        for key in ([("doi", ps.normalize_doi(p["doi"]))] if p["doi"] else []) + \
                   ([("arxiv", p["arxiv"])] if p["arxiv"] else []) + \
                   [("title", ps.normalize_title(p["title"]))]:
            if key in signals:
                return signals[key]
        return {"citations": None, "sources": set()}

    candidates = [(p, paper_signals(p)) for p in papers if p["status"] == "candidate"]
    candidates.sort(key=lambda x: (
        -(x[1]["citations"] if x[1]["citations"] is not None else -1),
        -(x[0]["year"] if x[0]["year"] is not None else 0),
        x[0]["id"],
    ))

    lines = [
        GENERATED_HEADER, "",
        "# Top Candidates", "",
        "Ranked by mechanical signals only (citation count, recency, source agreement).",
        "Relevance judgment belongs to the triage workflow, not this file.", "",
    ]
    if not candidates:
        lines.append("(no candidate papers)")
    for p, sig in candidates:
        year = p["year"] if p["year"] is not None else "n.d."
        venue = f", {p['venue']}" if p["venue"] else ""
        parts = []
        if sig["citations"] is not None:
            parts.append(f"citations: {sig['citations']}")
        if sig["sources"]:
            parts.append(f"sources: {', '.join(sorted(sig['sources']))}")
        detail = f"\n  - signals: {'; '.join(parts)}" if parts else ""
        note = f"\n  - {p['note']}" if p["note"] else ""
        lines.append(f"- **{p['id']}** — {p['title']} ({year}{venue}){detail}{note}")
    lines.append("")
    path = _lit_dir(base) / "TOP_CANDIDATES.md"
    path.write_text("\n".join(lines))
    return path


def cmd_search(base: Path, args) -> int:
    try:
        papers = ps.load(base)
    except ps.PapersError as e:
        print(f"ERROR: {e}")
        return 1

    per_source, warnings = src.search_all(
        args.query, args.limit, _cache_dir(base),
        only=args.source, refresh=args.refresh)
    for w in warnings:
        print(f"WARNING: {w} (source skipped)")
    if not per_source:
        print("All sources failed or were skipped; nothing to ingest.")
        print("Check network access, or retry later — results are cached once a source answers.")
        return 1

    added, skipped = [], []
    for hit in src.merge_hits(per_source):
        existing = _match_existing(papers, hit)
        if existing:
            skipped.append((hit["title"], existing["id"]))
        else:
            added.append(_add_paper(papers, hit, "search"))

    if added:
        ps.save(base, papers)
    top = write_top_candidates(base, papers)
    for paper in added:
        print(f"added: {paper['id']}  {paper['title']} [candidate]")
    for title, dup_id in skipped:
        print(f"skipped (already present as {dup_id}): {title}")
    queried = ", ".join(name for name, _ in per_source)
    print(f"{len(added)} added, {len(skipped)} skipped from {queried}. Total papers: {len(papers)}.")
    print(f"Ranked view: {top}")
    return 0


def cmd_dedup(base: Path) -> int:
    try:
        papers = ps.load(base)
    except ps.PapersError as e:
        print(f"ERROR: {e}")
        return 1

    definite: list[tuple[str, list[dict]]] = []
    seen: dict = {}
    for kind, keyfn in [
        ("doi", lambda p: ps.normalize_doi(p["doi"]) if p["doi"] else None),
        ("arxiv", lambda p: p["arxiv"]),
        ("title", lambda p: ps.normalize_title(p["title"])),
    ]:
        groups: dict = {}
        for p in papers:
            k = keyfn(p)
            if k:
                groups.setdefault(k, []).append(p)
        for k, group in sorted(groups.items()):
            ids = tuple(sorted(x["id"] for x in group))
            if len(group) > 1 and ids not in seen:
                seen[ids] = True
                definite.append((kind, group))

    fuzzy = []
    norm = [(p, ps.normalize_title(p["title"])) for p in papers]
    for i in range(len(norm)):
        for j in range(i + 1, len(norm)):
            a, ta = norm[i]
            b, tb = norm[j]
            if ta == tb:
                continue  # already a definite duplicate
            # near-identical, or one title extends the other (trailing subtitle/edition marker)
            if (difflib.SequenceMatcher(None, ta, tb).ratio() >= FUZZY_THRESHOLD
                    or ta.startswith(tb + " ") or tb.startswith(ta + " ")):
                fuzzy.append((a, b))

    if not definite and not fuzzy:
        print(f"No duplicates found across {len(papers)} papers.")
        return 0
    for kind, group in definite:
        ids = ", ".join(x["id"] for x in group)
        print(f"DUPLICATE ({kind}): {ids}")
        for x in group:
            print(f"  {x['id']}: {x['title']} ({x['year']}, added {x['added']})")
        print("  -> keep one, then remove the other via a hand edit you make yourself;")
        print("     the CLI never merges entries automatically.")
    for a, b in fuzzy:
        print(f"REVIEW_REQUIRED (near-identical titles): {a['id']} vs {b['id']}")
        print(f"  {a['id']}: {a['title']}")
        print(f"  {b['id']}: {b['title']}")
    return 0


def cmd_queue(base: Path, limit) -> int:
    try:
        papers = ps.load(base)
    except ps.PapersError as e:
        print(f"ERROR: {e}")
        return 1
    reading = [p for p in papers if p["status"] == "reading"]
    queued = [p for p in papers if p["status"] == "queued"]
    if limit is not None:
        queued = queued[:max(0, limit - len(reading))]
    if not reading and not queued:
        print("Reading queue is empty (no papers with status queued/reading).")
        return 0
    for label, group in [("reading", reading), ("queued", queued)]:
        if group:
            print(f"{label}:")
            for p in group:
                year = p["year"] if p["year"] is not None else "n.d."
                print(f"  {p['id']}  {p['title']} ({year})")
                if p["note"]:
                    print(f"    note: {p['note']}")
    return 0


def cmd_mark(base: Path, paper_id: str, status, decision, roles=None, note=None) -> int:
    if status is None and roles is None and note is None:
        print("Nothing to change: pass a status, --role, and/or --note.")
        return 1
    try:
        papers = ps.load(base)
    except ps.PapersError as e:
        print(f"ERROR: {e}")
        return 1
    paper = next((p for p in papers if p["id"] == paper_id), None)
    if paper is None:
        print(f"No paper with id: {paper_id}")
        return 1

    if status is not None and status in ps.GATED_STATUSES:
        if not decision:
            print(f"Refusing: '{status}' is a gated status.")
            print("Promotions to read/proposed_cite/cited/rejected require an approved decision.")
            print("Append a proposal to .nora/decisions/decisions.yaml, get it approved, then:")
            print(f"  nora literature mark {paper_id} {status} --decision <decision-id>")
            return 1
        decisions = read_decisions(base)
        if decision not in decisions:
            print(f"Refusing: decision {decision} not found in .nora/decisions/decisions.yaml.")
            return 1
        if decisions[decision] != "approved":
            print(f"Refusing: decision {decision} has status '{decisions[decision]}', not 'approved'.")
            print("Only the user approves decisions; a pending proposal is not an approval.")
            return 1
        paper["decision"] = decision

    changes = []
    if status is not None:
        old = paper["status"]
        paper["status"] = status
        changes.append(f"{old} -> {status}" + (f" (decision {decision})" if status in ps.GATED_STATUSES else ""))
    if roles is not None:
        paper["roles"] = roles
        changes.append(f"roles: [{', '.join(roles)}]" if roles else "roles cleared")
    if note is not None:
        paper["note"] = _clean(note) or None
        changes.append("note updated")
    paper["updated"] = _today()
    ps.save(base, papers)
    print(f"{paper_id}: " + "; ".join(changes))
    return 0


def _coverage_lines(papers: list[dict]) -> list[str]:
    lines = [f"Papers: {len(papers)} total"]
    counts = {s: 0 for s in ps.STATUSES}
    for p in papers:
        counts[p["status"]] += 1
    lines.append("  " + "  ".join(f"{s}: {counts[s]}" for s in ps.STATUSES))
    lines.append("")
    lines.append("Role coverage (a paper can hold several roles):")
    unassigned = 0
    role_counts = {r: 0 for r in ps.ROLES}
    for p in papers:
        if not p["roles"]:
            unassigned += 1
        for r in p["roles"]:
            if r in role_counts:
                role_counts[r] += 1
    for r in ps.ROLES:
        if role_counts[r]:
            lines.append(f"  {r}: {role_counts[r]}")
    if unassigned:
        lines.append(f"  unassigned (no roles yet): {unassigned}")
    gaps = [r for r in ps.ROLES if not role_counts[r] and r != "other"]
    if gaps:
        lines.append("")
        lines.append(f"Gaps (roles with no papers): {', '.join(gaps)}")
    return lines


def cmd_coverage(base: Path, write: bool = False) -> int:
    try:
        papers = ps.load(base)
    except ps.PapersError as e:
        print(f"ERROR: {e}")
        return 1
    lines = _coverage_lines(papers)
    print("\n".join(lines))
    if write:
        path = _lit_dir(base) / "COVERAGE_REPORT.md"
        path.write_text("\n".join(
            [GENERATED_HEADER, "", "# Coverage Report", "", "```text"] + lines + ["```", ""]))
        print()
        print(f"Written: {path}")
    return 0


def cmd_render(base: Path) -> int:
    try:
        papers = ps.load(base)
    except ps.PapersError as e:
        print(f"ERROR: {e}")
        return 1
    lit = _lit_dir(base)

    def line(p: dict) -> str:
        year = p["year"] if p["year"] is not None else "n.d."
        venue = f", {p['venue']}" if p["venue"] else ""
        out = f"- **{p['id']}** — {p['title']} ({year}{venue})"
        if p["note"]:
            out += f"\n  - {p['note']}"
        return out

    queue_lines = [GENERATED_HEADER, "", "# Reading Queue", ""]
    for label, status in [("Reading now", "reading"), ("Queued", "queued")]:
        group = [p for p in papers if p["status"] == status]
        queue_lines += [f"## {label}", ""]
        queue_lines += [line(p) for p in group] if group else ["(none)"]
        queue_lines.append("")
    (lit / "READING_QUEUE.md").write_text("\n".join(queue_lines))

    map_lines = [GENERATED_HEADER, "", "# Related Work Map", ""]
    for role in ps.ROLES:
        group = [p for p in papers if role in p["roles"]]
        if not group:
            continue
        map_lines += [f"## {role}", ""]
        map_lines += [line(p) + f" — `{p['status']}`" for p in group]
        map_lines.append("")
    unassigned = [p for p in papers if not p["roles"]]
    if unassigned:
        map_lines += ["## (no role assigned yet)", ""]
        map_lines += [line(p) + f" — `{p['status']}`" for p in unassigned]
        map_lines.append("")
    (lit / "RELATED_WORK_MAP.md").write_text("\n".join(map_lines))
    top = write_top_candidates(base, papers)

    print("Rendered from papers.yaml:")
    print(f"  {lit / 'READING_QUEUE.md'}")
    print(f"  {lit / 'RELATED_WORK_MAP.md'}")
    print(f"  {top}")
    return 0


def doctor_lines(base: Path) -> tuple[list[str], bool]:
    """Literature health check lines (OK/INFO/WARNING prefixed) + healthy flag.

    Shared by 'nora literature doctor' and the module tier of 'nora doctor'.
    Legacy layout and not-yet-initialized states are the caller's concern;
    this assumes .nora/literature/ exists.
    """
    lit = _lit_dir(base)
    if not ps.papers_path(base).is_file():
        if any((lit / f).is_file() for f in LEGACY_FILES):
            return [
                "INFO: pre-0.4 literature layout (markdown files, no papers.yaml).",
                "INFO: the module was redesigned; move old files aside and re-run 'nora literature init'.",
            ], True
        return ["WARNING: .nora/literature/papers.yaml missing (literature module initialized but incomplete)"], False

    try:
        papers = ps.load(base)
    except ps.PapersError as e:
        return [
            f"WARNING: {e}",
            "WARNING: papers.yaml is CLI-owned; restore it or re-create entries via 'nora literature ingest'.",
        ], False

    lines = [f"OK: papers.yaml parses ({len(papers)} papers)"]
    healthy = True
    if (lit / "PAPER_NOTES").is_dir():
        lines.append("OK: .nora/literature/PAPER_NOTES/")
    else:
        lines.append("WARNING: .nora/literature/PAPER_NOTES/ missing")
        healthy = False

    decisions = read_decisions(base)
    gate_ok = True
    for p in papers:
        if p["status"] in ps.GATED_STATUSES:
            if not p["decision"]:
                lines.append(f"WARNING: {p['id']} is '{p['status']}' (gated) with no decision recorded")
                gate_ok = False
            elif decisions.get(p["decision"]) != "approved":
                found = decisions.get(p["decision"], "missing")
                lines.append(
                    f"WARNING: {p['id']} is '{p['status']}' but decision {p['decision']} is {found}, not approved")
                gate_ok = False
        bad_roles = [r for r in p["roles"] if r not in ps.ROLES]
        if bad_roles:
            lines.append(f"WARNING: {p['id']} has unknown roles: {', '.join(bad_roles)}")
            healthy = False
    if gate_ok:
        lines.append("OK: decision gate consistent (all gated statuses reference approved decisions)")
    return lines, healthy and gate_ok


def cmd_doctor(base: Path) -> int:
    if not _lit_dir(base).is_dir():
        print("ERROR: .nora/literature/ not found.")
        print("Run 'nora literature init' first.")
        return 1
    print("Checking literature state...")
    lines, healthy = doctor_lines(base)
    for line in lines:
        print(line)
    if healthy:
        print("Literature state looks OK.")
        return 0
    print("Literature state has problems (see WARNINGs above).")
    return 1


# --- dispatch ----------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="nora literature", add_help=True)
    sub = parser.add_subparsers(dest="subcmd")

    search = sub.add_parser("search", help="search external sources for candidate papers")
    search.add_argument("--query", required=True)
    search.add_argument("--source", choices=src.SOURCE_NAMES, help="restrict to one source")
    search.add_argument("--limit", type=int, default=10)
    search.add_argument("--refresh", action="store_true",
                        help="bypass the permanent response cache")

    ingest = sub.add_parser("ingest", help="add candidate papers")
    ingest.add_argument("--bibtex", metavar="FILE")
    ingest.add_argument("--titles", metavar="FILE")
    ingest.add_argument("--title")
    ingest.add_argument("--author", action="append", metavar="'Lastname, Firstname'")
    ingest.add_argument("--year", type=int)
    ingest.add_argument("--venue")
    ingest.add_argument("--doi")
    ingest.add_argument("--arxiv")
    ingest.add_argument("--url")
    ingest.add_argument("--note")

    sub.add_parser("dedup", help="report likely duplicates")

    queue = sub.add_parser("queue", help="list queued/reading papers")
    queue.add_argument("--limit", type=int)

    mark = sub.add_parser("mark", help="change a paper's status, roles, or note")
    mark.add_argument("id")
    mark.add_argument("status", nargs="?", choices=ps.STATUSES)
    mark.add_argument("--decision", metavar="ID")
    mark.add_argument("--role", action="append", choices=ps.ROLES, metavar="ROLE",
                      help="replace the paper's roles (repeatable)")
    mark.add_argument("--note", help="replace the paper's one-line relevance note")

    coverage = sub.add_parser("coverage", help="role x status coverage report")
    coverage.add_argument("--write", action="store_true",
                          help="also write COVERAGE_REPORT.md")
    sub.add_parser("render", help="regenerate markdown views")
    sub.add_parser("init", help="create .nora/literature/")
    sub.add_parser("doctor", help="check literature state")

    return parser


def cmd_literature(argv: list[str]) -> int:
    if not argv or argv[0] == "help":
        print(HELP_TEXT)
        return 0
    try:
        args = build_parser().parse_args(argv)
    except SystemExit as e:
        return int(e.code or 0)

    base = _base()
    if args.subcmd == "init":
        return cmd_init(base)
    if args.subcmd == "search":
        return cmd_search(base, args)
    if args.subcmd == "ingest":
        return cmd_ingest(base, args)
    if args.subcmd == "dedup":
        return cmd_dedup(base)
    if args.subcmd == "queue":
        return cmd_queue(base, args.limit)
    if args.subcmd == "mark":
        return cmd_mark(base, args.id, args.status, args.decision, args.role, args.note)
    if args.subcmd == "coverage":
        return cmd_coverage(base, args.write)
    if args.subcmd == "render":
        return cmd_render(base)
    if args.subcmd == "doctor":
        return cmd_doctor(base)
    print(HELP_TEXT)
    return 0
