"""nora writing — deterministic prose guardrails (Stage 8).

`nora writing lint` runs seven mechanical checks over .tex sources. All of
them are read-only: unlike `nora citation fix`, the writing domain offers no
apply path at all — quote direction, punctuation, and reference style are
context-sensitive enough that every change goes through a human (or a
propose-then-confirm skill workflow).

Checks and their frozen constraints:
- \\work placeholder commands are agent-misuse artifacts: BLOCKED, never
  formalized into a real macro
- long-sentence and emphasis-density checks are explicitly heuristics —
  their findings are leads, not verdicts
- \\usepackage policing is an agent rule (AGENTS.md approval list), not a
  lint check; the third-party `dtrt` package is out of scope
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

HELP_TEXT = """\
Nora writing assistant

Commands:
  nora writing init    Create .nora/writing/ skeleton in the current project
  nora writing lint    Mechanical prose checks over .tex files (read-only;
                       --write saves LINT_REPORT.md)
  nora writing doctor  Check whether writing module files exist

Lint checks: \\work placeholders (BLOCKED), leftover draft markup/markers
(TODO/FIXME/??/\\hl/...), hand-written Figure/Table/Section references that
should be \\cref, straight "..." quotes that should be ``...'' (code contexts
excluded), bold/italic overuse, overlong sentences (heuristic), and non-ASCII
punctuation. Nothing is ever modified — the writing domain has no apply path.

Judgment work (polish, restructure, overclaim-check, paragraph diagnosis,
style profile) stays in the skill:
  /nora-writing-assistant polish | restructure | overclaim-check | paragraph-diagnosis | style-profile"""

GENERATED_HEADER = "<!-- Generated by 'nora writing lint --write'. Do not edit by hand. -->"

SKIP_DIRS = {".git", ".nora", "node_modules", "__pycache__", ".venv", "venv",
             "build", "_build", "out"}

LONG_SENTENCE_WORDS = 40
EMPHASIS_MIN = 5
EMPHASIS_WORDS_PER = 200

DISCOURAGED_CMDS = re.compile(r"\\(hl|underline|uline|sout|marginpar)\b")
LEFTOVER_MARKERS = re.compile(r"\b(TODO|FIXME|XXX)\b|\?\?")
WORK_PLACEHOLDER = re.compile(r"\\work\b")
HANDWRITTEN_REF = re.compile(
    r"\b(Figure|Fig\.|Figs\.|Table|Tab\.|Section|Sec\.|Equation|Eq\.|Algorithm|Appendix)"
    r"\s*~?\s*\\ref\{")
HARDCODED_NUMBER = re.compile(r"\b(Figure|Table|Section)\s+[0-9]+\b")
EMPHASIS = re.compile(r"\\(textbf|textit|emph)\{")

# Keys as \u escapes so no ASCII lookalike can sneak in.
NON_ASCII_PUNCT = {
    "，": ",", "。": ".", "；": ";", "：": ":",  # fullwidth , . ; :
    "！": "!", "？": "?",                                # fullwidth ! ?
    "“": "``", "”": "''", "‘": "`", "’": "'",  # curly quotes
    "、": ",", "《": "", "》": "",                   # 、 《 》
    "（": "(", "）": ")", "【": "[", "】": "]",  # （ ） 【 】
    "—": "---", "…": "\\dots", "·": "",           # — … ·
}
assert all(ord(c) > 127 for c in NON_ASCII_PUNCT)

CODE_ENVS = ["verbatim", "verbatim*", "lstlisting", "minted", "Verbatim", "alltt"]


def _base() -> Path:
    from .cli import find_workspace_root
    return find_workspace_root() or Path.cwd()


def _discover(base: Path) -> list[Path]:
    found = []
    for path in sorted(base.rglob("*.tex")):
        if not any(part in SKIP_DIRS or part.startswith("_minted")
                   for part in path.relative_to(base).parts):
            found.append(path)
    return found


def strip_comments(text: str) -> str:
    return "\n".join(re.sub(r"(?<!\\)%.*", "", line) for line in text.splitlines())


def blank_code_contexts(text: str) -> str:
    """Blank out code contexts (keeping line numbers stable) so quote and
    punctuation checks skip them: verbatim-family environments, \\verb,
    \\lstinline, and \\texttt arguments."""
    def blank(m: re.Match) -> str:
        return re.sub(r"[^\n]", " ", m.group(0))

    for env in CODE_ENVS:
        text = re.sub(
            r"\\begin\{" + re.escape(env) + r"\}.*?\\end\{" + re.escape(env) + r"\}",
            blank, text, flags=re.DOTALL)
    text = re.sub(r"\\verb\*?(?P<d>[^A-Za-z\s])[^\n]*?(?P=d)", blank, text)
    text = re.sub(r"\\lstinline(?P<d>[^A-Za-z\s{])[^\n]*?(?P=d)", blank, text)
    text = re.sub(r"\\(lstinline|texttt)\{[^{}]*\}", blank, text)
    return text


def _finding(label: str, check: str, message: str) -> dict:
    return {"label": label, "check": check, "message": message}


def _per_line(text: str, regex: re.Pattern, path: Path, label: str, check: str,
              describe) -> list[dict]:
    findings = []
    for lineno, line in enumerate(text.splitlines(), 1):
        for m in regex.finditer(line):
            findings.append(_finding(label, check, describe(m, f"{path}:{lineno}")))
    return findings


def lint_file(path: Path) -> list[dict]:
    raw = strip_comments(path.read_text())
    findings = []

    findings += _per_line(
        raw, WORK_PLACEHOLDER, path, "BLOCKED", "work_placeholder",
        lambda m, loc: f"\\work placeholder at {loc} — agent-misuse artifact; remove it, never formalize it")
    findings += _per_line(
        raw, DISCOURAGED_CMDS, path, "REVIEW_REQUIRED", "discouraged_command",
        lambda m, loc: f"\\{m.group(1)} at {loc} (draft/markup command, discouraged in final prose)")
    findings += _per_line(
        raw, LEFTOVER_MARKERS, path, "REVIEW_REQUIRED", "leftover_marker",
        lambda m, loc: f"leftover marker '{m.group(0)}' at {loc}"
        + (" (often a broken \\ref)" if m.group(0) == "??" else ""))
    findings += _per_line(
        raw, HANDWRITTEN_REF, path, "REVIEW_REQUIRED", "handwritten_ref",
        lambda m, loc: f"'{m.group(1)} \\ref{{...}}' at {loc} — use \\cref (adding cleveref needs user approval)")
    findings += _per_line(
        raw, HARDCODED_NUMBER, path, "REVIEW_REQUIRED", "hardcoded_ref",
        lambda m, loc: f"hard-coded '{m.group(0)}' at {loc} — numbers drift; use \\cref with a label")

    # quote + punctuation checks skip code contexts
    prose = blank_code_contexts(raw)
    for lineno, line in enumerate(prose.splitlines(), 1):
        if '"' in line:
            findings.append(_finding(
                "REVIEW_REQUIRED", "straight_quotes",
                f'straight "..." quotes at {path}:{lineno} — use ``...\'\' in LaTeX prose '
                "(code contexts are exempt)"))
        for ch in line:
            if ch in NON_ASCII_PUNCT:
                hint = NON_ASCII_PUNCT[ch]
                suggestion = f" -> {hint}" if hint else " (no ASCII equivalent; rephrase)"
                findings.append(_finding(
                    "REVIEW_REQUIRED", "non_ascii_punct",
                    f"non-ASCII punctuation '{ch}' at {path}:{lineno}{suggestion}"))

    # emphasis density (one summary finding per file, not per hit)
    words = len(re.sub(r"\\[a-zA-Z]+|\$[^$]*\$", " ", prose).split())
    emphasis_hits = [(i + 1) for i, line in enumerate(prose.splitlines())
                     for _ in EMPHASIS.finditer(line)]
    threshold = max(EMPHASIS_MIN, words // EMPHASIS_WORDS_PER)
    if len(emphasis_hits) > threshold:
        top = ", ".join(str(n) for n in emphasis_hits[:5])
        findings.append(_finding(
            "REVIEW_REQUIRED", "emphasis_overuse",
            f"{len(emphasis_hits)} \\textbf/\\textit/\\emph in {path} "
            f"(~{words} words, threshold {threshold}); first lines: {top}. "
            "Captions/headings are counted too — judge in context."))

    # long sentences (heuristic)
    flat = re.sub(r"\$[^$]*\$|\\\([^)]*\\\)", " MATH ", prose)
    flat = re.sub(r"\\(cite|ref|label|cref|Cref)\w*\s*(\[[^\]]*\])?\s*\{[^}]*\}", " REF ", flat)
    for m in re.finditer(r"[^.!?]+[.!?]", flat):
        sentence = m.group(0)
        if sentence.lstrip().startswith("\\"):
            continue
        count = len(sentence.split())
        if count > LONG_SENTENCE_WORDS:
            lineno = flat[:m.start()].count("\n") + 1
            snippet = " ".join(sentence.split())[:90]
            findings.append(_finding(
                "REVIEW_REQUIRED", "long_sentence",
                f'heuristic: {count}-word sentence at {path}:~{lineno}: "{snippet}..."'))
    return findings


def cmd_lint(base: Path, args) -> int:
    texs = [Path(t) for t in args.tex] if args.tex else _discover(base)
    if not texs:
        print("No .tex files found in the workspace.")
        return 1
    print(f"Scanning {len(texs)} .tex file(s)...")
    findings = []
    for tex in texs:
        findings += lint_file(tex)

    lines = []
    if not findings:
        lines.append("No findings. Prose guardrails are clean.")
    order = {"BLOCKED": 0, "REVIEW_REQUIRED": 1}
    for f in sorted(findings, key=lambda f: order.get(f["label"], 2)):
        lines.append(f"{f['label']} [{f['check']}] {f['message']}")
    print("\n".join(lines))
    print()
    blocked = sum(1 for f in findings if f["label"] == "BLOCKED")
    print(f"{len(findings)} finding(s), {blocked} blocking.")
    print("Nothing was modified; the writing domain has no auto-apply path.")

    if args.write:
        report = base / ".nora" / "writing" / "LINT_REPORT.md"
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text("\n".join(
            [GENERATED_HEADER, "", "# Writing Lint Report", "",
             f"- Files: {len(texs)} .tex", "", "```text"] + lines + ["```", ""]))
        print(f"Written: {report}")
    return 1 if blocked else 0


def cmd_module_init(base: Path) -> int:
    from .cli import nora_home
    import shutil
    mod_dir = base / ".nora" / "writing"
    if mod_dir.is_dir():
        print("Writing state already exists: .nora/writing/")
        return 0
    mod_dir.mkdir(parents=True)
    src = nora_home() / "skills" / "nora-writing-assistant" / "templates" / "writing"
    for item in src.iterdir():
        shutil.copy(item, mod_dir / item.name)
    if not (base / ".nora" / "PROJECT_STATE.yaml").is_file():
        print("Note: no full Nora project state found (.nora/PROJECT_STATE.yaml missing).")
        print("Initialized writing-only (standalone) state in:")
    else:
        print("Initialized writing state in:")
    print(f"  {mod_dir}")
    return 0


def cmd_module_doctor(base: Path) -> int:
    from .cli import MODULES
    mod = MODULES["writing"]
    mod_dir = base / ".nora" / "writing"
    if not mod_dir.is_dir():
        print("ERROR: .nora/writing/ not found.")
        print("Run 'nora writing init' first.")
        return 1
    print(mod["doctor_intro"])
    missing = False
    for f in mod["files"]:
        if (base / f).is_file():
            print(f"OK: {f}")
        else:
            print(f"MISSING: {f}")
            missing = True
    if not missing:
        print(mod["doctor_ok"])
        return 0
    print(mod["doctor_incomplete"])
    return 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="nora writing", add_help=True)
    sub = parser.add_subparsers(dest="subcmd")
    lint = sub.add_parser("lint", help="mechanical prose checks (read-only)")
    lint.add_argument("--tex", action="append", metavar="FILE")
    lint.add_argument("--write", action="store_true", help="save LINT_REPORT.md")
    sub.add_parser("init", help="create .nora/writing/")
    sub.add_parser("doctor", help="check writing module state")
    return parser


def cmd_writing(argv: list[str]) -> int:
    if not argv or argv[0] == "help":
        print(HELP_TEXT)
        return 0
    try:
        args = build_parser().parse_args(argv)
    except SystemExit as e:
        return int(e.code or 0)
    base = _base()
    if args.subcmd == "lint":
        return cmd_lint(base, args)
    if args.subcmd == "init":
        return cmd_module_init(base)
    if args.subcmd == "doctor":
        return cmd_module_doctor(base)
    print(HELP_TEXT)
    return 0
